<?php

use Illuminate\Database\Seeder;

class PoMFieldtechTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('po_m_fieldtech')->delete();
        
        \DB::table('po_m_fieldtech')->insert(array (
            0 => 
            array (
                'id' => 1,
                'vendor_id' => 1,
                'nik' => '202001001',
                'name' => 'Pernardi Djojosudirdjo',
                'address' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'photo' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'vendor_id' => 1,
                'nik' => '202001002',
                'name' => 'Adelina Prasetio',
                'address' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'photo' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'vendor_id' => 1,
                'nik' => '202001003',
                'name' => 'Natalie Ong',
                'address' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'photo' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'vendor_id' => 1,
                'nik' => '202001004',
                'name' => 'Sutono Nitisastro',
                'address' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'photo' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'vendor_id' => 1,
                'nik' => '202001005',
                'name' => 'Natalie Tjahjadi',
                'address' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'photo' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'vendor_id' => 1,
                'nik' => '202001006',
                'name' => 'Perumahan Tegal Indah Permai',
                'address' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'photo' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'vendor_id' => 1,
                'nik' => '202001007',
                'name' => 'Suwandi Widjaja',
                'address' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'photo' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'vendor_id' => 1,
                'nik' => '202001008',
                'name' => 'Ong Wen Nio',
                'address' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'photo' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'vendor_id' => 2,
                'nik' => '202001009',
                'name' => 'Adi Sumito',
                'address' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'photo' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'vendor_id' => 2,
                'nik' => '202001010',
                'name' => 'Mrs Lina Ovani',
                'address' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'photo' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'vendor_id' => 2,
                'nik' => '202001011',
                'name' => 'Perseroan Terbatas',
                'address' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'photo' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'vendor_id' => 2,
                'nik' => '202001012',
                'name' => 'Mrs Josephine Budi Santoso',
                'address' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'photo' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'vendor_id' => 2,
                'nik' => '202001013',
                'name' => 'Adhi Utomo',
                'address' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'photo' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'vendor_id' => 2,
                'nik' => '202001014',
                'name' => 'Sutikno',
                'address' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'photo' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'vendor_id' => 2,
                'nik' => '202001015',
                'name' => 'Mrs Masiana Wijaya & Fam.',
                'address' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'photo' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}