<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

class CreateAuthModuleTable extends Migration {

	public function up()
	{
		Schema::create('auth_module', function(Blueprint $table)
		{
			$table->integer('id', true);
			$table->integer('type_id')->nullable()->index('type_id');
			$table->integer('parent')->nullable()->index('parent');
			$table->string('path')->nullable();
			$table->string('param')->nullable();
			$table->string('text', 50)->nullable()->default('');
			$table->string('icon', 50)->nullable()->default('');
			$table->string('route', 100)->nullable();
			$table->string('url')->nullable();
			$table->integer('sort')->nullable();
			$table->boolean('is_active')->nullable()->default(1);
			$table->boolean('is_locked')->nullable()->default(1);
			$table->string('auth', 100)->nullable()->unique('auth');
			$table->boolean('device')->nullable()->default(0);
			$table->string('description')->nullable();
			$table->char('created_by', 36)->nullable()->index('created_by');
			$table->char('updated_by', 36)->nullable()->index('updated_by');
            $table->timestamps();
		});

        \DB::table('auth_module')->insert(array (
            0 =>
                array (
                    'id' => 1439,
                    'type_id' => 100,
                    'parent' => NULL,
                    'path' => '/1439',
                    'param' => NULL,
                    'text' => 'System Administrator',
                    'icon' => 'fa-gear',
                    'route' => NULL,
                    'url' => NULL,
                    'sort' => 3,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => NULL,
                    'description' => NULL,
                    'created_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'updated_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'created_at' => '2020-03-25 07:24:47',
                    'updated_at' => '2020-07-13 12:37:09',
                ),
            1 =>
                array (
                    'id' => 1440,
                    'type_id' => 110,
                    'parent' => 1439,
                    'path' => '/1439/1440',
                    'param' => NULL,
                    'text' => 'User Manager',
                    'icon' => 'pe-7s-user',
                    'route' => 'auth.user',
                    'url' => NULL,
                    'sort' => 1,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => 0,
                    'description' => NULL,
                    'created_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'updated_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'created_at' => '2020-03-25 07:25:30',
                    'updated_at' => '2020-06-23 16:36:33',
                ),
            2 =>
                array (
                    'id' => 1441,
                    'type_id' => 310,
                    'parent' => 1440,
                    'path' => '/1439/1440/1441',
                    'param' => NULL,
                    'text' => 'Data',
                    'icon' => NULL,
                    'route' => 'auth.user.data',
                    'url' => NULL,
                    'sort' => 1,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => NULL,
                    'description' => NULL,
                    'created_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'updated_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'created_at' => '2020-03-25 07:26:41',
                    'updated_at' => '2020-03-29 14:32:44',
                ),
            3 =>
                array (
                    'id' => 1442,
                    'type_id' => 310,
                    'parent' => 1440,
                    'path' => '/1439/1440/1442',
                    'param' => NULL,
                    'text' => 'Push',
                    'icon' => NULL,
                    'route' => 'auth.user.push',
                    'url' => NULL,
                    'sort' => 3,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => NULL,
                    'description' => NULL,
                    'created_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'updated_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'created_at' => '2020-03-25 08:02:46',
                    'updated_at' => '2020-07-13 12:53:05',
                ),
            4 =>
                array (
                    'id' => 1443,
                    'type_id' => 310,
                    'parent' => 1440,
                    'path' => '/1439/1440/1443',
                    'param' => NULL,
                    'text' => 'Set Role',
                    'icon' => NULL,
                    'route' => 'auth.user.set.role',
                    'url' => NULL,
                    'sort' => 4,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => NULL,
                    'description' => NULL,
                    'created_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'updated_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'created_at' => '2020-03-25 08:03:08',
                    'updated_at' => '2020-07-13 12:53:05',
                ),
            5 =>
                array (
                    'id' => 1444,
                    'type_id' => 310,
                    'parent' => 1440,
                    'path' => '/1439/1440/1444',
                    'param' => NULL,
                    'text' => 'Set Password',
                    'icon' => NULL,
                    'route' => 'auth.user.set.password',
                    'url' => NULL,
                    'sort' => 5,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => NULL,
                    'description' => NULL,
                    'created_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'updated_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'created_at' => '2020-03-25 08:03:29',
                    'updated_at' => '2020-07-13 12:53:05',
                ),
            6 =>
                array (
                    'id' => 1445,
                    'type_id' => 310,
                    'parent' => 1440,
                    'path' => '/1439/1440/1445',
                    'param' => NULL,
                    'text' => 'Delete',
                    'icon' => NULL,
                    'route' => 'auth.user.delete',
                    'url' => NULL,
                    'sort' => 6,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => NULL,
                    'description' => NULL,
                    'created_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'updated_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'created_at' => '2020-03-25 08:03:48',
                    'updated_at' => '2020-07-13 12:53:05',
                ),
            7 =>
                array (
                    'id' => 1446,
                    'type_id' => 310,
                    'parent' => 1440,
                    'path' => '/1439/1440/1446',
                    'param' => NULL,
                    'text' => 'Force Delete',
                    'icon' => NULL,
                    'route' => 'auth.user.forcedelete',
                    'url' => NULL,
                    'sort' => 7,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => NULL,
                    'description' => NULL,
                    'created_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'updated_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'created_at' => '2020-03-25 08:04:09',
                    'updated_at' => '2020-07-13 12:53:05',
                ),
            8 =>
                array (
                    'id' => 1447,
                    'type_id' => 310,
                    'parent' => 1440,
                    'path' => '/1439/1440/1447',
                    'param' => NULL,
                    'text' => 'Restore',
                    'icon' => NULL,
                    'route' => 'auth.user.restore',
                    'url' => NULL,
                    'sort' => 8,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => NULL,
                    'description' => NULL,
                    'created_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'updated_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'created_at' => '2020-03-25 08:04:30',
                    'updated_at' => '2020-07-13 12:53:05',
                ),
            9 =>
                array (
                    'id' => 1448,
                    'type_id' => 110,
                    'parent' => 1439,
                    'path' => '/1439/1448',
                    'param' => NULL,
                    'text' => 'Module Manager',
                    'icon' => 'pe-7s-config',
                    'route' => 'auth.module',
                    'url' => NULL,
                    'sort' => 2,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => 0,
                    'description' => NULL,
                    'created_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'updated_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'created_at' => '2020-03-26 03:30:41',
                    'updated_at' => '2020-06-23 16:36:16',
                ),
            10 =>
                array (
                    'id' => 1449,
                    'type_id' => 310,
                    'parent' => 1448,
                    'path' => '/1439/1448/1449',
                    'param' => NULL,
                    'text' => 'Data',
                    'icon' => NULL,
                    'route' => 'auth.module.data',
                    'url' => NULL,
                    'sort' => 1,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => NULL,
                    'description' => NULL,
                    'created_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'updated_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'created_at' => '2020-03-26 03:31:13',
                    'updated_at' => '2020-03-29 14:32:44',
                ),
            11 =>
                array (
                    'id' => 1451,
                    'type_id' => 310,
                    'parent' => 1448,
                    'path' => '/1439/1448/1451',
                    'param' => NULL,
                    'text' => 'Create',
                    'icon' => NULL,
                    'route' => 'auth.module.create',
                    'url' => NULL,
                    'sort' => 2,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => NULL,
                    'description' => NULL,
                    'created_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'updated_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'created_at' => '2020-03-26 03:40:49',
                    'updated_at' => '2020-03-29 14:32:44',
                ),
            12 =>
                array (
                    'id' => 1452,
                    'type_id' => 310,
                    'parent' => 1448,
                    'path' => '/1439/1448/1452',
                    'param' => NULL,
                    'text' => 'Update',
                    'icon' => NULL,
                    'route' => 'auth.module.update',
                    'url' => NULL,
                    'sort' => 3,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => NULL,
                    'description' => NULL,
                    'created_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'updated_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'created_at' => '2020-03-26 03:44:42',
                    'updated_at' => '2020-03-29 14:32:44',
                ),
            13 =>
                array (
                    'id' => 1453,
                    'type_id' => 310,
                    'parent' => 1448,
                    'path' => '/1439/1448/1453',
                    'param' => NULL,
                    'text' => 'Delete',
                    'icon' => NULL,
                    'route' => 'auth.module.delete',
                    'url' => NULL,
                    'sort' => 4,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => NULL,
                    'description' => NULL,
                    'created_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'updated_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'created_at' => '2020-03-26 03:45:04',
                    'updated_at' => '2020-03-29 14:32:44',
                ),
            14 =>
                array (
                    'id' => 1454,
                    'type_id' => 310,
                    'parent' => 1448,
                    'path' => '/1439/1448/1454',
                    'param' => NULL,
                    'text' => 'Roles Update',
                    'icon' => NULL,
                    'route' => 'auth.module.update.roles',
                    'url' => NULL,
                    'sort' => 5,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => NULL,
                    'description' => NULL,
                    'created_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'updated_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'created_at' => '2020-03-26 03:45:46',
                    'updated_at' => '2020-03-29 14:32:44',
                ),
            15 =>
                array (
                    'id' => 1455,
                    'type_id' => 310,
                    'parent' => 1448,
                    'path' => '/1439/1448/1455',
                    'param' => NULL,
                    'text' => 'Field Update',
                    'icon' => NULL,
                    'route' => 'auth.module.update.field',
                    'url' => NULL,
                    'sort' => 6,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => NULL,
                    'description' => NULL,
                    'created_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'updated_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'created_at' => '2020-03-26 03:46:33',
                    'updated_at' => '2020-03-29 14:32:44',
                ),
            16 =>
                array (
                    'id' => 1456,
                    'type_id' => 310,
                    'parent' => 1448,
                    'path' => '/1439/1448/1456',
                    'param' => NULL,
                    'text' => 'Move Sorting',
                    'icon' => NULL,
                    'route' => 'auth.module.move',
                    'url' => NULL,
                    'sort' => 7,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => NULL,
                    'description' => NULL,
                    'created_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'updated_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'created_at' => '2020-03-26 03:47:00',
                    'updated_at' => '2020-03-29 14:32:44',
                ),
            17 =>
                array (
                    'id' => 1457,
                    'type_id' => 110,
                    'parent' => 1439,
                    'path' => '/1439/1457',
                    'param' => NULL,
                    'text' => 'Roles',
                    'icon' => 'pe-7s-edit',
                    'route' => 'auth.role',
                    'url' => NULL,
                    'sort' => 3,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => 0,
                    'description' => NULL,
                    'created_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'updated_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'created_at' => '2020-03-26 03:47:47',
                    'updated_at' => '2020-06-23 16:36:03',
                ),
            18 =>
                array (
                    'id' => 1462,
                    'type_id' => 310,
                    'parent' => 1457,
                    'path' => '/1439/1457/1462',
                    'param' => NULL,
                    'text' => 'Data',
                    'icon' => NULL,
                    'route' => 'auth.role.data',
                    'url' => NULL,
                    'sort' => 1,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => NULL,
                    'description' => NULL,
                    'created_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'updated_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'created_at' => '2020-05-09 21:07:36',
                    'updated_at' => '2020-05-09 21:07:36',
                ),
            19 =>
                array (
                    'id' => 1463,
                    'type_id' => 310,
                    'parent' => 1457,
                    'path' => '/1439/1457/1463',
                    'param' => NULL,
                    'text' => 'Data Module',
                    'icon' => NULL,
                    'route' => 'auth.role.data.module',
                    'url' => NULL,
                    'sort' => 2,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => NULL,
                    'description' => NULL,
                    'created_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'updated_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'created_at' => '2020-05-09 21:08:00',
                    'updated_at' => '2020-05-09 21:08:00',
                ),
            20 =>
                array (
                    'id' => 1465,
                    'type_id' => 310,
                    'parent' => 1457,
                    'path' => '/1439/1457/1465',
                    'param' => NULL,
                    'text' => 'Create',
                    'icon' => NULL,
                    'route' => 'auth.role.create',
                    'url' => NULL,
                    'sort' => 4,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => NULL,
                    'description' => NULL,
                    'created_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'updated_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'created_at' => '2020-05-09 21:11:01',
                    'updated_at' => '2020-05-09 21:11:01',
                ),
            21 =>
                array (
                    'id' => 1466,
                    'type_id' => 310,
                    'parent' => 1457,
                    'path' => '/1439/1457/1466',
                    'param' => NULL,
                    'text' => 'Update',
                    'icon' => NULL,
                    'route' => 'auth.role.update',
                    'url' => NULL,
                    'sort' => 5,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => NULL,
                    'description' => NULL,
                    'created_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'updated_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'created_at' => '2020-05-09 21:11:13',
                    'updated_at' => '2020-05-09 21:11:13',
                ),
            22 =>
                array (
                    'id' => 1467,
                    'type_id' => 310,
                    'parent' => 1457,
                    'path' => '/1439/1457/1467',
                    'param' => NULL,
                    'text' => 'Delete',
                    'icon' => NULL,
                    'route' => 'auth.role.delete',
                    'url' => NULL,
                    'sort' => 6,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => NULL,
                    'description' => NULL,
                    'created_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'updated_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'created_at' => '2020-05-09 21:11:27',
                    'updated_at' => '2020-05-09 21:11:27',
                ),
            23 =>
                array (
                    'id' => 1468,
                    'type_id' => 310,
                    'parent' => 1457,
                    'path' => '/1439/1457/1468',
                    'param' => NULL,
                    'text' => 'Set Home',
                    'icon' => NULL,
                    'route' => 'auth.role.set.home',
                    'url' => NULL,
                    'sort' => 7,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => NULL,
                    'description' => NULL,
                    'created_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'updated_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'created_at' => '2020-05-09 21:11:40',
                    'updated_at' => '2020-05-09 21:11:40',
                ),
            24 =>
                array (
                    'id' => 1469,
                    'type_id' => 310,
                    'parent' => 1457,
                    'path' => '/1439/1457/1469',
                    'param' => NULL,
                    'text' => 'Set Auth',
                    'icon' => NULL,
                    'route' => 'auth.role.set.auth',
                    'url' => NULL,
                    'sort' => 8,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => NULL,
                    'description' => NULL,
                    'created_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'updated_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'created_at' => '2020-05-09 21:11:54',
                    'updated_at' => '2020-05-09 21:11:54',
                ),
            25 =>
                array (
                    'id' => 1470,
                    'type_id' => 110,
                    'parent' => 1486,
                    'path' => '/1486/1470',
                    'param' => NULL,
                    'text' => 'Client',
                    'icon' => 'pe-7s-culture',
                    'route' => 'client',
                    'url' => NULL,
                    'sort' => 2,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => 0,
                    'description' => NULL,
                    'created_by' => '4bee41d0-9b2a-4f64-bf75-b9eafdba9c9e',
                    'updated_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'created_at' => '2020-06-23 10:55:43',
                    'updated_at' => '2020-06-23 16:32:40',
                ),
            26 =>
                array (
                    'id' => 1471,
                    'type_id' => 310,
                    'parent' => 1470,
                    'path' => '/1470/1471',
                    'param' => NULL,
                    'text' => 'Data',
                    'icon' => NULL,
                    'route' => 'client.data',
                    'url' => NULL,
                    'sort' => 1,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => NULL,
                    'description' => NULL,
                    'created_by' => '4bee41d0-9b2a-4f64-bf75-b9eafdba9c9e',
                    'updated_by' => '4bee41d0-9b2a-4f64-bf75-b9eafdba9c9e',
                    'created_at' => '2020-06-23 10:56:07',
                    'updated_at' => '2020-06-23 10:56:07',
                ),
            27 =>
                array (
                    'id' => 1472,
                    'type_id' => 310,
                    'parent' => 1470,
                    'path' => '/1470/1472',
                    'param' => NULL,
                    'text' => 'Push',
                    'icon' => NULL,
                    'route' => 'client.push',
                    'url' => NULL,
                    'sort' => 2,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => NULL,
                    'description' => NULL,
                    'created_by' => '4bee41d0-9b2a-4f64-bf75-b9eafdba9c9e',
                    'updated_by' => '4bee41d0-9b2a-4f64-bf75-b9eafdba9c9e',
                    'created_at' => '2020-06-23 10:56:24',
                    'updated_at' => '2020-06-23 10:56:25',
                ),
            28 =>
                array (
                    'id' => 1473,
                    'type_id' => 310,
                    'parent' => 1470,
                    'path' => '/1470/1473',
                    'param' => NULL,
                    'text' => 'Delete',
                    'icon' => NULL,
                    'route' => 'client.delete',
                    'url' => NULL,
                    'sort' => 3,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => NULL,
                    'description' => NULL,
                    'created_by' => '4bee41d0-9b2a-4f64-bf75-b9eafdba9c9e',
                    'updated_by' => '4bee41d0-9b2a-4f64-bf75-b9eafdba9c9e',
                    'created_at' => '2020-06-23 10:56:43',
                    'updated_at' => '2020-06-23 10:56:43',
                ),
            29 =>
                array (
                    'id' => 1474,
                    'type_id' => 110,
                    'parent' => 1486,
                    'path' => '/1486/1474',
                    'param' => NULL,
                    'text' => 'Vendor',
                    'icon' => 'pe-7s-science',
                    'route' => 'vendor',
                    'url' => NULL,
                    'sort' => 4,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => 0,
                    'description' => NULL,
                    'created_by' => '4bee41d0-9b2a-4f64-bf75-b9eafdba9c9e',
                    'updated_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'created_at' => '2020-06-23 11:00:29',
                    'updated_at' => '2020-06-23 16:32:40',
                ),
            30 =>
                array (
                    'id' => 1475,
                    'type_id' => 310,
                    'parent' => 1474,
                    'path' => '/1474/1475',
                    'param' => NULL,
                    'text' => 'Data',
                    'icon' => NULL,
                    'route' => 'vendor.data',
                    'url' => NULL,
                    'sort' => 1,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => NULL,
                    'description' => NULL,
                    'created_by' => '4bee41d0-9b2a-4f64-bf75-b9eafdba9c9e',
                    'updated_by' => '4bee41d0-9b2a-4f64-bf75-b9eafdba9c9e',
                    'created_at' => '2020-06-23 11:00:53',
                    'updated_at' => '2020-06-23 11:00:53',
                ),
            31 =>
                array (
                    'id' => 1476,
                    'type_id' => 310,
                    'parent' => 1474,
                    'path' => '/1474/1476',
                    'param' => NULL,
                    'text' => 'Push',
                    'icon' => NULL,
                    'route' => 'vendor.push',
                    'url' => NULL,
                    'sort' => 2,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => NULL,
                    'description' => NULL,
                    'created_by' => '4bee41d0-9b2a-4f64-bf75-b9eafdba9c9e',
                    'updated_by' => '4bee41d0-9b2a-4f64-bf75-b9eafdba9c9e',
                    'created_at' => '2020-06-23 11:01:30',
                    'updated_at' => '2020-06-23 11:01:30',
                ),
            32 =>
                array (
                    'id' => 1477,
                    'type_id' => 310,
                    'parent' => 1474,
                    'path' => '/1474/1477',
                    'param' => NULL,
                    'text' => 'Delete',
                    'icon' => NULL,
                    'route' => 'vendor.delete',
                    'url' => NULL,
                    'sort' => 3,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => NULL,
                    'description' => NULL,
                    'created_by' => '4bee41d0-9b2a-4f64-bf75-b9eafdba9c9e',
                    'updated_by' => '4bee41d0-9b2a-4f64-bf75-b9eafdba9c9e',
                    'created_at' => '2020-06-23 11:01:54',
                    'updated_at' => '2020-06-23 11:01:54',
                ),
            33 =>
                array (
                    'id' => 1478,
                    'type_id' => 110,
                    'parent' => 1486,
                    'path' => '/1486/1478',
                    'param' => NULL,
                    'text' => 'Fieldtech',
                    'icon' => 'pe-7s-users',
                    'route' => 'fieldtech',
                    'url' => NULL,
                    'sort' => 3,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => 0,
                    'description' => NULL,
                    'created_by' => '4bee41d0-9b2a-4f64-bf75-b9eafdba9c9e',
                    'updated_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'created_at' => '2020-06-23 11:04:09',
                    'updated_at' => '2020-06-23 16:32:40',
                ),
            34 =>
                array (
                    'id' => 1479,
                    'type_id' => 310,
                    'parent' => 1478,
                    'path' => '/1478/1479',
                    'param' => NULL,
                    'text' => 'Data',
                    'icon' => NULL,
                    'route' => 'fieldtech.data',
                    'url' => NULL,
                    'sort' => 1,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => NULL,
                    'description' => NULL,
                    'created_by' => '4bee41d0-9b2a-4f64-bf75-b9eafdba9c9e',
                    'updated_by' => '4bee41d0-9b2a-4f64-bf75-b9eafdba9c9e',
                    'created_at' => '2020-06-23 11:04:27',
                    'updated_at' => '2020-06-23 11:04:27',
                ),
            35 =>
                array (
                    'id' => 1480,
                    'type_id' => 310,
                    'parent' => 1478,
                    'path' => '/1478/1480',
                    'param' => NULL,
                    'text' => 'Push',
                    'icon' => NULL,
                    'route' => 'fieldtech.push',
                    'url' => NULL,
                    'sort' => 2,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => NULL,
                    'description' => NULL,
                    'created_by' => '4bee41d0-9b2a-4f64-bf75-b9eafdba9c9e',
                    'updated_by' => '4bee41d0-9b2a-4f64-bf75-b9eafdba9c9e',
                    'created_at' => '2020-06-23 11:04:45',
                    'updated_at' => '2020-06-23 11:04:45',
                ),
            36 =>
                array (
                    'id' => 1481,
                    'type_id' => 310,
                    'parent' => 1478,
                    'path' => '/1478/1481',
                    'param' => NULL,
                    'text' => 'Delete',
                    'icon' => NULL,
                    'route' => 'fieldtech.delete',
                    'url' => NULL,
                    'sort' => 3,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => NULL,
                    'description' => NULL,
                    'created_by' => '4bee41d0-9b2a-4f64-bf75-b9eafdba9c9e',
                    'updated_by' => '4bee41d0-9b2a-4f64-bf75-b9eafdba9c9e',
                    'created_at' => '2020-06-23 11:05:04',
                    'updated_at' => '2020-06-23 11:05:04',
                ),
            37 =>
                array (
                    'id' => 1482,
                    'type_id' => 110,
                    'parent' => 1486,
                    'path' => '/1486/1482',
                    'param' => NULL,
                    'text' => 'Site',
                    'icon' => 'pe-7s-map-marker',
                    'route' => 'site',
                    'url' => NULL,
                    'sort' => 1,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => 0,
                    'description' => NULL,
                    'created_by' => '4bee41d0-9b2a-4f64-bf75-b9eafdba9c9e',
                    'updated_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'created_at' => '2020-06-23 11:08:16',
                    'updated_at' => '2020-06-23 16:28:23',
                ),
            38 =>
                array (
                    'id' => 1483,
                    'type_id' => 310,
                    'parent' => 1482,
                    'path' => '/1482/1483',
                    'param' => NULL,
                    'text' => 'Data',
                    'icon' => NULL,
                    'route' => 'site.data',
                    'url' => NULL,
                    'sort' => 1,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => NULL,
                    'description' => NULL,
                    'created_by' => '4bee41d0-9b2a-4f64-bf75-b9eafdba9c9e',
                    'updated_by' => '4bee41d0-9b2a-4f64-bf75-b9eafdba9c9e',
                    'created_at' => '2020-06-23 11:11:39',
                    'updated_at' => '2020-06-23 11:11:52',
                ),
            39 =>
                array (
                    'id' => 1484,
                    'type_id' => 310,
                    'parent' => 1482,
                    'path' => '/1482/1484',
                    'param' => NULL,
                    'text' => 'Push',
                    'icon' => NULL,
                    'route' => 'site.push',
                    'url' => NULL,
                    'sort' => 2,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => NULL,
                    'description' => NULL,
                    'created_by' => '4bee41d0-9b2a-4f64-bf75-b9eafdba9c9e',
                    'updated_by' => '4bee41d0-9b2a-4f64-bf75-b9eafdba9c9e',
                    'created_at' => '2020-06-23 11:12:07',
                    'updated_at' => '2020-06-23 11:12:08',
                ),
            40 =>
                array (
                    'id' => 1485,
                    'type_id' => 310,
                    'parent' => 1482,
                    'path' => '/1482/1485',
                    'param' => NULL,
                    'text' => 'Delete',
                    'icon' => NULL,
                    'route' => 'site.delete',
                    'url' => NULL,
                    'sort' => 3,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => NULL,
                    'description' => NULL,
                    'created_by' => '4bee41d0-9b2a-4f64-bf75-b9eafdba9c9e',
                    'updated_by' => '4bee41d0-9b2a-4f64-bf75-b9eafdba9c9e',
                    'created_at' => '2020-06-23 11:12:20',
                    'updated_at' => '2020-06-23 11:12:20',
                ),
            41 =>
                array (
                    'id' => 1486,
                    'type_id' => 100,
                    'parent' => NULL,
                    'path' => '/1486',
                    'param' => NULL,
                    'text' => 'Database',
                    'icon' => NULL,
                    'route' => NULL,
                    'url' => NULL,
                    'sort' => 2,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => 2,
                    'description' => NULL,
                    'created_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'updated_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'created_at' => '2020-06-23 16:25:35',
                    'updated_at' => '2020-07-03 07:06:56',
                ),
            42 =>
                array (
                    'id' => 1487,
                    'type_id' => 110,
                    'parent' => 1486,
                    'path' => '/1486/1487',
                    'param' => NULL,
                    'text' => 'Service',
                    'icon' => 'fa-tag',
                    'route' => 'service',
                    'url' => NULL,
                    'sort' => 5,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => 0,
                    'description' => NULL,
                    'created_by' => '4bee41d0-9b2a-4f64-bf75-b9eafdba9c9e',
                    'updated_by' => '4bee41d0-9b2a-4f64-bf75-b9eafdba9c9e',
                    'created_at' => '2020-06-30 14:16:26',
                    'updated_at' => '2020-06-30 14:19:14',
                ),
            43 =>
                array (
                    'id' => 1488,
                    'type_id' => 310,
                    'parent' => 1487,
                    'path' => '/1486/1487/1488',
                    'param' => NULL,
                    'text' => 'Data',
                    'icon' => NULL,
                    'route' => 'service.data',
                    'url' => NULL,
                    'sort' => 1,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => NULL,
                    'description' => NULL,
                    'created_by' => '4bee41d0-9b2a-4f64-bf75-b9eafdba9c9e',
                    'updated_by' => '4bee41d0-9b2a-4f64-bf75-b9eafdba9c9e',
                    'created_at' => '2020-06-30 14:16:42',
                    'updated_at' => '2020-06-30 14:16:42',
                ),
            44 =>
                array (
                    'id' => 1489,
                    'type_id' => 310,
                    'parent' => 1487,
                    'path' => '/1486/1487/1489',
                    'param' => NULL,
                    'text' => 'Push',
                    'icon' => NULL,
                    'route' => 'service.push',
                    'url' => NULL,
                    'sort' => 2,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => NULL,
                    'description' => NULL,
                    'created_by' => '4bee41d0-9b2a-4f64-bf75-b9eafdba9c9e',
                    'updated_by' => '4bee41d0-9b2a-4f64-bf75-b9eafdba9c9e',
                    'created_at' => '2020-06-30 14:16:55',
                    'updated_at' => '2020-06-30 14:16:55',
                ),
            45 =>
                array (
                    'id' => 1490,
                    'type_id' => 310,
                    'parent' => 1487,
                    'path' => '/1486/1487/1490',
                    'param' => NULL,
                    'text' => 'Delete',
                    'icon' => NULL,
                    'route' => 'site.delete',
                    'url' => NULL,
                    'sort' => 3,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => NULL,
                    'description' => NULL,
                    'created_by' => '4bee41d0-9b2a-4f64-bf75-b9eafdba9c9e',
                    'updated_by' => '4bee41d0-9b2a-4f64-bf75-b9eafdba9c9e',
                    'created_at' => '2020-06-30 14:17:08',
                    'updated_at' => '2020-06-30 14:17:08',
                ),
            46 =>
                array (
                    'id' => 1491,
                    'type_id' => 100,
                    'parent' => NULL,
                    'path' => '/1491',
                    'param' => NULL,
                    'text' => 'Work Order',
                    'icon' => NULL,
                    'route' => NULL,
                    'url' => NULL,
                    'sort' => 1,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => 0,
                    'description' => NULL,
                    'created_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'updated_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'created_at' => '2020-07-03 07:06:56',
                    'updated_at' => '2020-07-03 07:23:40',
                ),
            47 =>
                array (
                    'id' => 1492,
                    'type_id' => 110,
                    'parent' => 1491,
                    'path' => '/1491/1492',
                    'param' => NULL,
                    'text' => 'Ongoing',
                    'icon' => 'pe-7s-rocket',
                    'route' => 'wo',
                    'url' => NULL,
                    'sort' => 1,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => 0,
                    'description' => NULL,
                    'created_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'updated_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'created_at' => '2020-07-03 07:09:57',
                    'updated_at' => '2020-07-03 07:23:52',
                ),
            48 =>
                array (
                    'id' => 1493,
                    'type_id' => 110,
                    'parent' => 1491,
                    'path' => '/1491/1493',
                    'param' => NULL,
                    'text' => 'Add Ticket',
                    'icon' => 'pe-7s-file',
                    'route' => 'wo.form',
                    'url' => NULL,
                    'sort' => 2,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => NULL,
                    'description' => NULL,
                    'created_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'updated_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'created_at' => '2020-07-03 07:20:23',
                    'updated_at' => '2020-07-03 07:23:52',
                ),
            49 =>
                array (
                    'id' => 1494,
                    'type_id' => 110,
                    'parent' => 1491,
                    'path' => '/1491/1494',
                    'param' => NULL,
                    'text' => 'Archive',
                    'icon' => 'pe-7s-folder',
                    'route' => 'wo.archive',
                    'url' => NULL,
                    'sort' => 3,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => NULL,
                    'description' => NULL,
                    'created_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'updated_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'created_at' => '2020-07-03 07:21:57',
                    'updated_at' => '2020-07-03 07:23:52',
                ),
            50 =>
                array (
                    'id' => 1496,
                    'type_id' => 310,
                    'parent' => 1492,
                    'path' => '/1491/1492/1496',
                    'param' => NULL,
                    'text' => 'Data',
                    'icon' => NULL,
                    'route' => 'wo.data',
                    'url' => NULL,
                    'sort' => 1,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => NULL,
                    'description' => NULL,
                    'created_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'updated_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'created_at' => '2020-07-13 12:31:04',
                    'updated_at' => '2020-07-13 12:34:56',
                ),
            51 =>
                array (
                    'id' => 1497,
                    'type_id' => 310,
                    'parent' => 1494,
                    'path' => '/1491/1494/1497',
                    'param' => NULL,
                    'text' => 'Data Archive',
                    'icon' => NULL,
                    'route' => 'wo.data.archive',
                    'url' => NULL,
                    'sort' => 1,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => NULL,
                    'description' => NULL,
                    'created_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'updated_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'created_at' => '2020-07-13 12:31:35',
                    'updated_at' => '2020-07-13 12:36:50',
                ),
            52 =>
                array (
                    'id' => 1498,
                    'type_id' => 310,
                    'parent' => 1491,
                    'path' => '/1491/1498',
                    'param' => NULL,
                    'text' => 'Data Fieldtech',
                    'icon' => NULL,
                    'route' => 'wo.data.fieldtech',
                    'url' => NULL,
                    'sort' => 5,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => NULL,
                    'description' => NULL,
                    'created_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'updated_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'created_at' => '2020-07-13 12:32:04',
                    'updated_at' => '2020-07-13 12:37:26',
                ),
            53 =>
                array (
                    'id' => 1499,
                    'type_id' => 310,
                    'parent' => 1491,
                    'path' => '/1491/1499',
                    'param' => NULL,
                    'text' => 'Push',
                    'icon' => NULL,
                    'route' => 'wo.push',
                    'url' => NULL,
                    'sort' => 6,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => NULL,
                    'description' => NULL,
                    'created_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'updated_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'created_at' => '2020-07-13 12:32:36',
                    'updated_at' => '2020-07-13 12:37:26',
                ),
            54 =>
                array (
                    'id' => 1500,
                    'type_id' => 310,
                    'parent' => 1491,
                    'path' => '/1491/1500',
                    'param' => NULL,
                    'text' => 'Push Action',
                    'icon' => NULL,
                    'route' => 'wo.push.action',
                    'url' => NULL,
                    'sort' => 7,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => NULL,
                    'description' => NULL,
                    'created_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'updated_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'created_at' => '2020-07-13 12:32:55',
                    'updated_at' => '2020-07-13 12:37:26',
                ),
            55 =>
                array (
                    'id' => 1501,
                    'type_id' => 310,
                    'parent' => 1491,
                    'path' => '/1491/1501',
                    'param' => NULL,
                    'text' => 'Delete',
                    'icon' => NULL,
                    'route' => 'wo.delete',
                    'url' => NULL,
                    'sort' => 8,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => NULL,
                    'description' => NULL,
                    'created_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'updated_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'created_at' => '2020-07-13 12:33:10',
                    'updated_at' => '2020-07-13 12:37:26',
                ),
            56 =>
                array (
                    'id' => 1502,
                    'type_id' => 310,
                    'parent' => 1491,
                    'path' => '/1491/1502',
                    'param' => NULL,
                    'text' => 'Data Site',
                    'icon' => NULL,
                    'route' => 'wo.data.site',
                    'url' => NULL,
                    'sort' => 4,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => NULL,
                    'description' => NULL,
                    'created_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'updated_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'created_at' => '2020-07-13 12:37:09',
                    'updated_at' => '2020-07-13 12:37:26',
                ),
            57 =>
                array (
                    'id' => 1503,
                    'type_id' => 310,
                    'parent' => 1440,
                    'path' => '/1439/1440/1503',
                    'param' => NULL,
                    'text' => 'Data Fieldtech',
                    'icon' => NULL,
                    'route' => 'auth.user.data.fieldtech',
                    'url' => NULL,
                    'sort' => 2,
                    'is_active' => 1,
                    'is_locked' => 1,
                    'auth' => NULL,
                    'device' => NULL,
                    'description' => NULL,
                    'created_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'updated_by' => '394c94ca-d220-4799-83a8-d6ccafc0b1af',
                    'created_at' => '2020-07-13 12:53:01',
                    'updated_at' => '2020-07-13 12:53:06',
                ),
        ));
    }

	public function down()
	{
		Schema::drop('auth_module');
	}

}
